:bug: Use execute_script so we don't have to worry about clicking the actual button whose position changes
Otherwise, we get an
ElementClickInterceptedException: Message: element click intercepted:
Element <a id="loadmorelink" href="javascript:loadPage();" style="">...</a>
is not clickable at point (540, 664). Other element would receive the
click: <div id="recrow23760816" class="listing">...</div>